// @generated by protoc-gen-es v2.6.1 with parameter "target=ts,keep_empty_files=true"
// @generated from file google/api/authz.proto (package google.api, syntax proto3)
/* eslint-disable */
/**
 * @fileoverview added by tsickle
 * Generated from: blaze-out/k8-fastbuild/bin/google/api/authz_pb.ts
 * @suppress {checkTypes} added by tsickle
 * @suppress {extraRequire} added by tsickle
 * @suppress {missingRequire} added by tsickle
 * @suppress {uselessCode} added by tsickle
 * @suppress {suspiciousCode} added by tsickle
 * @suppress {missingReturn} added by tsickle
 * @suppress {unusedLocalVariables} added by tsickle
 * @suppress {missingOverride} added by tsickle
 * @suppress {const} added by tsickle
 */
goog.module('google3.google.api.authz_pb');
var module = module || { id: 'google/api/authz_pb.closure.js' };
goog.require('google3.third_party.javascript.tslib.tslib');
const codegenv2_1 = goog.require('google3.third_party.javascript.bufbuild_protobuf.src.codegenv2.index');
const inclusion_pb_1 = goog.require('google3.google.api.inclusion_pb');
const descriptor_pb_1 = goog.require('google3.net.proto2.proto.descriptor_pb');
/**
 * Describes the file google/api/authz.proto.
 * @type {?}
 */
exports.file_google_api_authz = (0, codegenv2_1.fileDesc)("ChZnb29nbGUvYXBpL2F1dGh6LnByb3RvEgpnb29nbGUuYXBpIjoKEUF1dGhvcml6YXRpb25SdWxlEhAKCHNlbGVjdG9yGAEgASgJEhMKC3Blcm1pc3Npb25zGAIgASgJOkwKBWF1dGh6EhQucHJvdG8yLkZpZWxkT3B0aW9ucxixhIs5IAEoCzIdLmdvb2dsZS5hcGkuQXV0aG9yaXphdGlvblJ1bGVSBWF1dGh6QnoKDmNvbS5nb29nbGUuYXBpQgpBdXRoelByb3RvUAFaRWdvb2dsZS5nb2xhbmcub3JnL2dlbnByb3RvL2dvb2dsZWFwaXMvYXBpL3NlcnZpY2Vjb25maWc7c2VydmljZWNvbmZpZ/gBAaICBEdBUEmK1dvSDwUKA2FsbGIGcHJvdG8z", [inclusion_pb_1.file_google_api_inclusion, descriptor_pb_1.file_net_proto2_proto_descriptor]);
/**
 * Authorization rule for API services.
 *
 * It specifies the permission(s) required for an API element for the overall
 * API request to succeed. It is typically used to mark request message fields
 * that contain the name of the resource and indicates the permissions that
 * will be checked on that resource.
 *
 * For example:
 *
 *     package google.storage.v1;
 *
 *     message CopyObjectRequest {
 *       string source = 1 [
 *         (google.api.authz).permissions = "storage.objects.get"];
 *
 *       string destination = 2 [
 *         (google.api.authz).permissions =
 *             "storage.objects.create,storage.objects.update"];
 *     }
 *
 *
 * \@generated from message google.api.AuthorizationRule
 * @typedef {?}
 */
exports.AuthorizationRule;
/**
 * Describes the message google.api.AuthorizationRule.
 * Use `create(AuthorizationRuleSchema)` to create a new message.
 * @type {?}
 */
exports.AuthorizationRuleSchema = (0, codegenv2_1.messageDesc)(exports.file_google_api_authz, 0);
/**
 * See `AuthorizationRule`.
 *
 * \@generated from extension: google.api.AuthorizationRule authz = 119718449;
 * @type {?}
 */
exports.authz = (0, codegenv2_1.extDesc)(exports.file_google_api_authz, 0);
