// @generated by protoc-gen-es v2.6.1 with parameter "target=ts,keep_empty_files=true"
// @generated from file google/api/inclusion.proto (package google.api, syntax proto3)
/* eslint-disable */
/**
 * @fileoverview added by tsickle
 * Generated from: blaze-out/k8-fastbuild/bin/google/api/inclusion_pb.ts
 * @suppress {checkTypes} added by tsickle
 * @suppress {extraRequire} added by tsickle
 * @suppress {missingRequire} added by tsickle
 * @suppress {uselessCode} added by tsickle
 * @suppress {suspiciousCode} added by tsickle
 * @suppress {missingReturn} added by tsickle
 * @suppress {unusedLocalVariables} added by tsickle
 * @suppress {missingOverride} added by tsickle
 * @suppress {const} added by tsickle
 */
goog.module('google3.google.api.inclusion_pb');
var module = module || { id: 'google/api/inclusion_pb.closure.js' };
goog.require('google3.third_party.javascript.tslib.tslib');
const codegenv2_1 = goog.require('google3.third_party.javascript.bufbuild_protobuf.src.codegenv2.index');
const visibility_pb_1 = goog.require('google3.google.api.visibility_pb');
const descriptor_pb_1 = goog.require('google3.net.proto2.proto.descriptor_pb');
/**
 * Describes the file google/api/inclusion.proto.
 * @type {?}
 */
exports.file_google_api_inclusion = (0, codegenv2_1.fileDesc)("Chpnb29nbGUvYXBpL2luY2x1c2lvbi5wcm90bxIKZ29vZ2xlLmFwaSI3CgxBcGlJbmNsdXNpb24SDgoGc2NvcGVzGAEgAygJOhf60uSTAhESD0dPT0dMRV9JTlRFUk5BTDpoCglpbmNsdXNpb24SEy5wcm90bzIuRmlsZU9wdGlvbnMY0bqr+gEgASgLMhguZ29vZ2xlLmFwaS5BcGlJbmNsdXNpb25CF/rS5JMCERIPR09PR0xFX0lOVEVSTkFMUglpbmNsdXNpb25CawoOY29tLmdvb2dsZS5hcGlCDkluY2x1c2lvblByb3RvUAFaPWdvb2dsZS5nb2xhbmcub3JnL2dlbnByb3RvL2dvb2dsZWFwaXMvYXBpL2luY2x1c2lvbjtpbmNsdXNpb274AQGiAgRHQVBJYgZwcm90bzM", [visibility_pb_1.file_google_api_visibility, descriptor_pb_1.file_net_proto2_proto_descriptor]);
/**
 * `Inclusion` specifies whether the proto definitions in a file are includable
 * into API surfaces and under what conditions.
 *
 * \@generated from message google.api.ApiInclusion
 * @typedef {?}
 */
exports.ApiInclusion;
/**
 * Describes the message google.api.ApiInclusion.
 * Use `create(ApiInclusionSchema)` to create a new message.
 * @type {?}
 */
exports.ApiInclusionSchema = (0, codegenv2_1.messageDesc)(exports.file_google_api_inclusion, 0);
/**
 * \@generated from extension: google.api.ApiInclusion inclusion = 525000017;
 * @type {?}
 */
exports.inclusion = (0, codegenv2_1.extDesc)(exports.file_google_api_inclusion, 0);
