// (== page versioning ==)
// @generated by protoc-gen-es v2.6.1 with parameter "target=ts,keep_empty_files=true"
// @generated from file google/api/versioning.proto (package google.api, syntax proto3)
/* eslint-disable */
/**
 * @fileoverview added by tsickle
 * Generated from: blaze-out/k8-fastbuild/bin/google/api/versioning_pb.ts
 * @suppress {checkTypes} added by tsickle
 * @suppress {extraRequire} added by tsickle
 * @suppress {missingRequire} added by tsickle
 * @suppress {uselessCode} added by tsickle
 * @suppress {suspiciousCode} added by tsickle
 * @suppress {missingReturn} added by tsickle
 * @suppress {unusedLocalVariables} added by tsickle
 * @suppress {missingOverride} added by tsickle
 * @suppress {const} added by tsickle
 */
goog.module('google3.google.api.versioning_pb');
var module = module || { id: 'google/api/versioning_pb.closure.js' };
goog.require('google3.third_party.javascript.tslib.tslib');
const codegenv2_1 = goog.require('google3.third_party.javascript.bufbuild_protobuf.src.codegenv2.index');
const descriptor_pb_1 = goog.require('google3.net.proto2.proto.descriptor_pb');
/**
 * Describes the file google/api/versioning.proto.
 * @type {?}
 */
exports.file_google_api_versioning = (0, codegenv2_1.fileDesc)("Chtnb29nbGUvYXBpL3ZlcnNpb25pbmcucHJvdG8SCmdvb2dsZS5hcGkiNwoOVmVyc2lvbmluZ1J1bGUSEAoIc2VsZWN0b3IYASABKAkSEwoLcmVzdHJpY3Rpb24YAiABKAkimAEKElZlcnNpb25pbmdGaWxlSW5mbxIVCg1vcmlnaW5hbF9uYW1lGAEgASgJEh4KFm9yaWdpbmFsX3Byb3RvX3BhY2thZ2UYAiABKAkSFwoPbmV3X2FwaV92ZXJzaW9uGAMgASgJEjIKFW9yaWdpbmFsX2ZpbGVfb3B0aW9ucxgEIAEoCzITLnByb3RvMi5GaWxlT3B0aW9uczpoChR2ZXJzaW9uaW5nX2ZpbGVfaW5mbxITLnByb3RvMi5GaWxlT3B0aW9ucxiJ17R0IAEoCzIeLmdvb2dsZS5hcGkuVmVyc2lvbmluZ0ZpbGVJbmZvUhJ2ZXJzaW9uaW5nRmlsZUluZm86XAoOYXBpX3ZlcnNpb25pbmcSFi5wcm90bzIuU2VydmljZU9wdGlvbnMYzqOcRCABKAsyGi5nb29nbGUuYXBpLlZlcnNpb25pbmdSdWxlUg1hcGlWZXJzaW9uaW5nOmEKEW1ldGhvZF92ZXJzaW9uaW5nEhUucHJvdG8yLk1ldGhvZE9wdGlvbnMYzqOcRCABKAsyGi5nb29nbGUuYXBpLlZlcnNpb25pbmdSdWxlUhBtZXRob2RWZXJzaW9uaW5nOmQKEm1lc3NhZ2VfdmVyc2lvbmluZxIWLnByb3RvMi5NZXNzYWdlT3B0aW9ucxjOo5xEIAEoCzIaLmdvb2dsZS5hcGkuVmVyc2lvbmluZ1J1bGVSEW1lc3NhZ2VWZXJzaW9uaW5nOl4KEGZpZWxkX3ZlcnNpb25pbmcSFC5wcm90bzIuRmllbGRPcHRpb25zGM6jnEQgASgLMhouZ29vZ2xlLmFwaS5WZXJzaW9uaW5nUnVsZVIPZmllbGRWZXJzaW9uaW5nOlsKD2VudW1fdmVyc2lvbmluZxITLnByb3RvMi5FbnVtT3B0aW9ucxjOo5xEIAEoCzIaLmdvb2dsZS5hcGkuVmVyc2lvbmluZ1J1bGVSDmVudW1WZXJzaW9uaW5nOmIKEHZhbHVlX3ZlcnNpb25pbmcSGC5wcm90bzIuRW51bVZhbHVlT3B0aW9ucxjOo5xEIAEoCzIaLmdvb2dsZS5hcGkuVmVyc2lvbmluZ1J1bGVSD3ZhbHVlVmVyc2lvbmluZ0JtCg5jb20uZ29vZ2xlLmFwaUIPVmVyc2lvbmluZ1Byb3RvUAFaQWdvb2dsZS5nb2xhbmcub3JnL2dlbnByb3RvL2dvb2dsZWFwaXMvYXBpL2Fubm90YXRpb25zO2Fubm90YXRpb25zogIER0FQSWIGcHJvdG8z", [descriptor_pb_1.file_net_proto2_proto_descriptor]);
/**
 * `Versioning` defines which proto elements (and their options) are present in
 * when a per-version copy is made of the containing package during build-time
 * processing of the service's proto definition. See
 * go/api-version-selector-user-guide for more details.
 *
 * \@generated from message google.api.VersioningRule
 * @typedef {?}
 */
exports.VersioningRule;
/**
 * Describes the message google.api.VersioningRule.
 * Use `create(VersioningRuleSchema)` to create a new message.
 * @type {?}
 */
exports.VersioningRuleSchema = (0, codegenv2_1.messageDesc)(exports.file_google_api_versioning, 0);
/**
 * A VersioningFileInfo is populated and added to the generated (versioned) file
 * descriptor objects to allow its consumers (e.g. OP tools) to know that the
 * file descriptor was versioned and from what "main" proto it was derived.
 *
 * \@generated from message google.api.VersioningFileInfo
 * @typedef {?}
 */
exports.VersioningFileInfo;
/**
 * Describes the message google.api.VersioningFileInfo.
 * Use `create(VersioningFileInfoSchema)` to create a new message.
 * @type {?}
 */
exports.VersioningFileInfoSchema = (0, codegenv2_1.messageDesc)(exports.file_google_api_versioning, 1);
/**
 * \@generated from extension: google.api.VersioningFileInfo versioning_file_info = 244132745;
 * @type {?}
 */
exports.versioning_file_info = (0, codegenv2_1.extDesc)(exports.file_google_api_versioning, 0);
/**
 * \@generated from extension: google.api.VersioningRule api_versioning = 143069646;
 * @type {?}
 */
exports.api_versioning = (0, codegenv2_1.extDesc)(exports.file_google_api_versioning, 1);
/**
 * \@generated from extension: google.api.VersioningRule method_versioning = 143069646;
 * @type {?}
 */
exports.method_versioning = (0, codegenv2_1.extDesc)(exports.file_google_api_versioning, 2);
/**
 * \@generated from extension: google.api.VersioningRule message_versioning = 143069646;
 * @type {?}
 */
exports.message_versioning = (0, codegenv2_1.extDesc)(exports.file_google_api_versioning, 3);
/**
 * \@generated from extension: google.api.VersioningRule field_versioning = 143069646;
 * @type {?}
 */
exports.field_versioning = (0, codegenv2_1.extDesc)(exports.file_google_api_versioning, 4);
/**
 * \@generated from extension: google.api.VersioningRule enum_versioning = 143069646;
 * @type {?}
 */
exports.enum_versioning = (0, codegenv2_1.extDesc)(exports.file_google_api_versioning, 5);
/**
 * \@generated from extension: google.api.VersioningRule value_versioning = 143069646;
 * @type {?}
 */
exports.value_versioning = (0, codegenv2_1.extDesc)(exports.file_google_api_versioning, 6);
