/**
 * @fileoverview added by tsickle
 * Generated from: devtools/cider/extensions/jetski/diff_zones/inline_diff_manager.ts
 * @suppress {checkTypes} added by tsickle
 * @suppress {extraRequire} added by tsickle
 * @suppress {missingRequire} added by tsickle
 * @suppress {uselessCode} added by tsickle
 * @suppress {suspiciousCode} added by tsickle
 * @suppress {missingReturn} added by tsickle
 * @suppress {unusedLocalVariables} added by tsickle
 * @suppress {missingOverride} added by tsickle
 * @suppress {const} added by tsickle
 */
goog.module('google3.devtools.cider.extensions.jetski.diff_zones.inline_diff_manager');
var module = module || { id: 'devtools/cider/extensions/jetski/diff_zones/inline_diff_manager.closure.js' };
goog.require('google3.third_party.javascript.tslib.tslib');
const tsickle_vscode_1 = goog.requireType("vscode");
const tsickle_diff_helper_2 = goog.requireType("google3.devtools.cider.extensions.jetski.diff_zones.diff_helper");
const tsickle_hunk_storage_3 = goog.requireType("google3.devtools.cider.extensions.jetski.diff_zones.hunk_storage");
const tsickle_inline_diff_changes_4 = goog.requireType("google3.devtools.cider.extensions.jetski.diff_zones.inline_diff_changes");
const tsickle_inline_diff_range_tracker_5 = goog.requireType("google3.devtools.cider.extensions.jetski.diff_zones.inline_diff_range_tracker");
const tsickle_utils_6 = goog.requireType("google3.devtools.cider.extensions.jetski.diff_zones.utils");
const tsickle_inline_diff_change_range_7 = goog.requireType("google3.devtools.cider.extensions.jetski.diff_zones.inline_diff_change_range");
const vscode = goog.require('vscode'); // from //devtools/cider/extensions:vscode
// from //devtools/cider/extensions:vscode
const diff_helper_1 = goog.require('google3.devtools.cider.extensions.jetski.diff_zones.diff_helper');
const hunk_storage_1 = goog.require('google3.devtools.cider.extensions.jetski.diff_zones.hunk_storage');
const inline_diff_changes_1 = goog.require('google3.devtools.cider.extensions.jetski.diff_zones.inline_diff_changes');
const inline_diff_range_tracker_1 = goog.require('google3.devtools.cider.extensions.jetski.diff_zones.inline_diff_range_tracker');
const utils_1 = goog.require('google3.devtools.cider.extensions.jetski.diff_zones.utils');
/**
 * String representation of a vscode.Uri (via uri.toString())
 * @typedef {string}
 */
var FileUriStr;
/**
 * Represents an active inline diff session for a document.
 * @record
 */
function ActiveDiff() { }
exports.ActiveDiff = ActiveDiff;
/* istanbul ignore if */
if (false) {
    /**
     * @type {!tsickle_vscode_1.Uri}
     * @public
     */
    ActiveDiff.prototype.uri;
    /**
     * The baseline original text of the file before any edits were made.
     * @type {string}
     * @public
     */
    ActiveDiff.prototype.originalText;
    /**
     * The final target modified text generated by the agent.
     * @type {string}
     * @public
     */
    ActiveDiff.prototype.modifiedText;
    /**
     * The current intermediate text buffer in the editor, updating as hunks are accepted or rejected.
     * @type {string}
     * @public
     */
    ActiveDiff.prototype.combinedText;
    /**
     * @type {!tsickle_inline_diff_changes_4.InlineDiffChanges}
     * @public
     */
    ActiveDiff.prototype.changes;
    /**
     * @type {boolean}
     * @public
     */
    ActiveDiff.prototype.hasBeenShown;
}
/**
 * @record
 */
function DiffStyleGroup() { }
/* istanbul ignore if */
if (false) {
    /**
     * @type {!tsickle_vscode_1.TextEditorDecorationType}
     * @public
     */
    DiffStyleGroup.prototype.base;
    /**
     * @type {!tsickle_vscode_1.TextEditorDecorationType}
     * @public
     */
    DiffStyleGroup.prototype.single;
    /**
     * @type {!tsickle_vscode_1.TextEditorDecorationType}
     * @public
     */
    DiffStyleGroup.prototype.top;
    /**
     * @type {!tsickle_vscode_1.TextEditorDecorationType}
     * @public
     */
    DiffStyleGroup.prototype.mid;
    /**
     * @type {!tsickle_vscode_1.TextEditorDecorationType}
     * @public
     */
    DiffStyleGroup.prototype.bottom;
}
/**
 * @record
 */
function DiffStyles() { }
/* istanbul ignore if */
if (false) {
    /**
     * @type {!DiffStyleGroup}
     * @public
     */
    DiffStyles.prototype.add;
    /**
     * @type {!DiffStyleGroup}
     * @public
     */
    DiffStyles.prototype.delete;
}
/**
 * Manages in-editor inline diff reviews by temporarily editing the file buffer,
 * coloring line ranges, and overlaying Accept/Reject CodeLenses.
 * @extends {tsickle_vscode_1.Disposable}
 */
class InlineDiffManager {
    /**
     * @public
     */
    constructor() {
        this.activeDiffs = new Map();
        this.disposables = [];
        this.isResolvingHunk = false;
        this.onDidFinalizeFileEmitter = new vscode.EventEmitter();
        this.onDidFinalizeFile = this.onDidFinalizeFileEmitter.event;
        this.onDidResolveHunkEmitter = new vscode.EventEmitter();
        this.onDidResolveHunk = this.onDidResolveHunkEmitter.event;
        this.onDidChangeActiveDiffsEmitter = new vscode.EventEmitter();
        this.onDidChangeActiveDiffs = this.onDidChangeActiveDiffsEmitter.event;
        /** @type {string} */
        const BORDER_WIDTH = '1px';
        /** @type {string} */
        const BORDER_STYLE = 'solid';
        /** @type {!tsickle_vscode_1.ThemeColor} */
        const addBorderColor = new vscode.ThemeColor('diffEditor.insertedTextBorder');
        /** @type {!tsickle_vscode_1.ThemeColor} */
        const deleteBorderColor = new vscode.ThemeColor('diffEditor.removedTextBorder');
        this.styles = {
            add: {
                base: vscode.window.createTextEditorDecorationType({
                    backgroundColor: new vscode.ThemeColor('diffEditor.insertedTextBackground'),
                    isWholeLine: true,
                    rangeBehavior: vscode.DecorationRangeBehavior.ClosedClosed,
                }),
                single: vscode.window.createTextEditorDecorationType({
                    isWholeLine: true,
                    rangeBehavior: vscode.DecorationRangeBehavior.ClosedClosed,
                    borderWidth: BORDER_WIDTH,
                    borderStyle: BORDER_STYLE,
                    borderColor: addBorderColor,
                }),
                top: vscode.window.createTextEditorDecorationType({
                    isWholeLine: true,
                    rangeBehavior: vscode.DecorationRangeBehavior.ClosedClosed,
                    borderWidth: `${BORDER_WIDTH} ${BORDER_WIDTH} 0 ${BORDER_WIDTH}`,
                    borderStyle: BORDER_STYLE,
                    borderColor: addBorderColor,
                }),
                mid: vscode.window.createTextEditorDecorationType({
                    isWholeLine: true,
                    rangeBehavior: vscode.DecorationRangeBehavior.ClosedClosed,
                    borderWidth: `0 ${BORDER_WIDTH} 0 ${BORDER_WIDTH}`,
                    borderStyle: BORDER_STYLE,
                    borderColor: addBorderColor,
                }),
                bottom: vscode.window.createTextEditorDecorationType({
                    isWholeLine: true,
                    rangeBehavior: vscode.DecorationRangeBehavior.ClosedClosed,
                    borderWidth: `0 ${BORDER_WIDTH} ${BORDER_WIDTH} ${BORDER_WIDTH}`,
                    borderStyle: BORDER_STYLE,
                    borderColor: addBorderColor,
                }),
            },
            delete: {
                base: vscode.window.createTextEditorDecorationType({
                    backgroundColor: new vscode.ThemeColor('diffEditor.removedTextBackground'),
                    isWholeLine: true,
                    rangeBehavior: vscode.DecorationRangeBehavior.ClosedClosed,
                }),
                single: vscode.window.createTextEditorDecorationType({
                    isWholeLine: true,
                    rangeBehavior: vscode.DecorationRangeBehavior.ClosedClosed,
                    borderWidth: BORDER_WIDTH,
                    borderStyle: BORDER_STYLE,
                    borderColor: deleteBorderColor,
                }),
                top: vscode.window.createTextEditorDecorationType({
                    isWholeLine: true,
                    rangeBehavior: vscode.DecorationRangeBehavior.ClosedClosed,
                    borderWidth: `${BORDER_WIDTH} ${BORDER_WIDTH} 0 ${BORDER_WIDTH}`,
                    borderStyle: BORDER_STYLE,
                    borderColor: deleteBorderColor,
                }),
                mid: vscode.window.createTextEditorDecorationType({
                    isWholeLine: true,
                    rangeBehavior: vscode.DecorationRangeBehavior.ClosedClosed,
                    borderWidth: `0 ${BORDER_WIDTH} 0 ${BORDER_WIDTH}`,
                    borderStyle: BORDER_STYLE,
                    borderColor: deleteBorderColor,
                }),
                bottom: vscode.window.createTextEditorDecorationType({
                    isWholeLine: true,
                    rangeBehavior: vscode.DecorationRangeBehavior.ClosedClosed,
                    borderWidth: `0 ${BORDER_WIDTH} ${BORDER_WIDTH} ${BORDER_WIDTH}`,
                    borderStyle: BORDER_STYLE,
                    borderColor: deleteBorderColor,
                }),
            },
        };
        for (const group of [this.styles.add, this.styles.delete]) {
            for (const style of Object.values(group)) {
                this.disposables.push(style);
            }
        }
        this.codeLensProvider = new InlineDiffCodeLensProvider(this);
        this.disposables.push(vscode.workspace.registerTextDocumentContentProvider('antigravity-diff-original', new OriginalDocumentProvider(this)), vscode.languages.registerCodeLensProvider({ scheme: 'file' }, this.codeLensProvider), vscode.commands.registerCommand('antigravity.inlineDiff.accept', (/**
         * @param {(undefined|string|!tsickle_vscode_1.Uri)=} fileUriStr
         * @param {(undefined|number)=} index
         * @return {!Promise<void>}
         */
        (fileUriStr, index) => this.acceptHunk(fileUriStr, index))), vscode.commands.registerCommand('antigravity.inlineDiff.reject', (/**
         * @param {(undefined|string|!tsickle_vscode_1.Uri)=} fileUriStr
         * @param {(undefined|number)=} index
         * @return {!Promise<void>}
         */
        (fileUriStr, index) => this.rejectHunk(fileUriStr, index))), vscode.commands.registerCommand('antigravity.inlineDiff.acceptAll', (/**
         * @param {(undefined|string|!tsickle_vscode_1.Uri)=} fileUriStr
         * @return {!Promise<void>}
         */
        (fileUriStr) => this.acceptAll(fileUriStr))), vscode.commands.registerCommand('antigravity.inlineDiff.rejectAll', (/**
         * @param {(undefined|string|!tsickle_vscode_1.Uri)=} fileUriStr
         * @return {!Promise<void>}
         */
        (fileUriStr) => this.rejectAll(fileUriStr))), vscode.window.onDidChangeActiveTextEditor((/**
         * @param {(undefined|!tsickle_vscode_1.TextEditor)} editor
         * @return {void}
         */
        (editor) => {
            if (editor) {
                this.handleActiveEditorChange(editor).catch((/**
                 * @param {?} e
                 * @return {void}
                 */
                (e) => {
                    console.error('[Antigravity] Error handling active editor change:', e);
                }));
            }
        })), vscode.window.onDidChangeVisibleTextEditors((/**
         * @return {void}
         */
        () => {
            this.refreshAllVisibleDecorations();
        })), vscode.workspace.onDidChangeTextDocument((/**
         * @param {!tsickle_vscode_1.TextDocumentChangeEvent} event
         * @return {void}
         */
        (event) => {
            this.handleDocumentEdit(event);
        })), vscode.workspace.onDidCloseTextDocument((/**
         * @param {!tsickle_vscode_1.TextDocument} doc
         * @return {void}
         */
        (doc) => {
            this.handleDocumentClose(doc).catch((/**
             * @param {?} e
             * @return {void}
             */
            (e) => {
                console.error('[Antigravity] Error handling document close:', e);
            }));
        })));
        this.disposables.push(this.onDidChangeActiveDiffsEmitter, this.onDidFinalizeFileEmitter, this.onDidResolveHunkEmitter);
    }
    /**
     * @public
     * @param {string} uriStr
     * @return {(undefined|!ActiveDiff)}
     */
    getActiveDiff(uriStr) {
        return this.activeDiffs.get(uriStr);
    }
    /**
     * @public
     * @return {boolean}
     */
    hasActiveDiffs() {
        return this.activeDiffs.size > 0;
    }
    /**
     * Registers a new file diff and starts the in-editor review process.
     * @public
     * @param {!tsickle_vscode_1.Uri} uri
     * @param {string} originalText
     * @param {string} modifiedText
     * @return {!Promise<boolean>}
     */
    async registerDiff(uri, originalText, modifiedText) {
        /** @type {string} */
        const key = uri.toString();
        /** @type {!Array<!google3$third_party$javascript$typings$diff$index.Hunk>} */
        const hunks = (0, diff_helper_1.getDiffHunks)(originalText, modifiedText);
        if (hunks.length === 0) {
            console.info('[Antigravity] No differences found for:', key);
            return false;
        }
        if (this.activeDiffs.has(key)) {
            // Clear decorations in all visible editors of the obsolete session
            for (const editor of vscode.window.visibleTextEditors) {
                if (editor.document.uri.toString() === key) {
                    this.clearDecorations(editor);
                }
            }
            this.activeDiffs.delete(key);
        }
        /** @type {!tsickle_vscode_1.TextDocument} */
        const document = await vscode.workspace.openTextDocument(uri);
        /** @type {!tsickle_inline_diff_changes_4.InlineDiffChanges} */
        const changes = new inline_diff_changes_1.InlineDiffChanges();
        /** @type {!ActiveDiff} */
        const activeDiff = {
            uri,
            originalText,
            modifiedText,
            combinedText: (0, diff_helper_1.getTextWithHunks)(originalText, hunks),
            changes,
            hasBeenShown: true,
        };
        this.activeDiffs.set(key, activeDiff);
        await this.applyContentReplacement(document, activeDiff.combinedText);
        activeDiff.changes.setup(hunks, document);
        this.refreshVisibleEditorDecorations(key, activeDiff.changes);
        /** @type {(undefined|!tsickle_vscode_1.TextEditor)} */
        const activeEditor = vscode.window.activeTextEditor;
        if (activeEditor && activeEditor.document.uri.toString() === key) {
            await vscode.commands.executeCommand('setContext', 'antigravity.hasActiveDiff', true);
        }
        this.onDidChangeActiveDiffsEmitter.fire();
        return true;
    }
    /**
     * Accepts a specific hunk inside a file.
     * @public
     * @param {(undefined|string|!tsickle_vscode_1.Uri)=} targetUri
     * @param {(undefined|number)=} index
     * @return {!Promise<void>}
     */
    async acceptHunk(targetUri, index) {
        if (targetUri == null || index == null) {
            return;
        }
        /** @type {string} */
        const uriStr = typeof targetUri === 'string' ? targetUri : (/** @type {!tsickle_vscode_1.Uri} */ (targetUri)).toString();
        /** @type {(undefined|!ActiveDiff)} */
        const activeDiff = this.activeDiffs.get(uriStr);
        if (!activeDiff) {
            console.warn(`[Antigravity] acceptHunk failed: no active diff found for uriStr: ${uriStr}`);
            return;
        }
        /** @type {!tsickle_inline_diff_change_range_7.InlineDiffChangeRange} */
        const rangeToResolve = activeDiff.changes.ranges[index];
        if (!rangeToResolve) {
            console.warn(`[Antigravity] acceptHunk failed: no range found at index: ${index}`);
            return;
        }
        /** @type {!Array<string>} */
        const insertions = rangeToResolve.modifiedText
            ? rangeToResolve.modifiedText.split('\n')
            : [];
        /** @type {!Array<string>} */
        const deletions = rangeToResolve.originalText
            ? rangeToResolve.originalText.split('\n')
            : [];
        /** @type {string} */
        const hunkHash = (0, hunk_storage_1.computeHunkHash)(insertions, deletions);
        this.onDidResolveHunkEmitter.fire({
            uri: activeDiff.uri,
            hunkIndex: index,
            accept: true,
            hunkHash,
        });
        /** @type {!Array<!tsickle_inline_diff_change_range_7.InlineDiffChangeRange>} */
        const remainingRanges = activeDiff.changes.ranges.filter((/**
         * @param {!tsickle_inline_diff_change_range_7.InlineDiffChangeRange} _
         * @param {number} i
         * @return {boolean}
         */
        (_, i) => i !== index));
        /** @type {!tsickle_vscode_1.TextDocument} */
        const document = await vscode.workspace.openTextDocument(activeDiff.uri);
        if (rangeToResolve.deletionRange) {
            /** @type {!tsickle_vscode_1.Range} */
            const rangeToDelete = new vscode.Range(rangeToResolve.deletionRange.start, document.lineAt(rangeToResolve.deletionRange.end.line).rangeIncludingLineBreak.end);
            /** @type {!tsickle_vscode_1.WorkspaceEdit} */
            const edit = new vscode.WorkspaceEdit();
            edit.delete(activeDiff.uri, rangeToDelete);
            this.isResolvingHunk = true;
            await vscode.workspace.applyEdit(edit);
            this.isResolvingHunk = false;
            /** @type {!tsickle_vscode_1.TextDocumentContentChangeEvent} */
            const changeEvent = {
                range: rangeToDelete,
                text: '',
                rangeLength: document.offsetAt(rangeToDelete.end) -
                    document.offsetAt(rangeToDelete.start),
                rangeOffset: document.offsetAt(rangeToDelete.start),
            };
            activeDiff.changes.ranges = (0, inline_diff_range_tracker_1.recalculateInlineDiffRanges)(remainingRanges, [
                changeEvent,
            ]);
        }
        else {
            activeDiff.changes.ranges = remainingRanges;
        }
        activeDiff.combinedText = document.getText();
        if (document.isDirty) {
            await document.save();
        }
        if (activeDiff.changes.ranges.length === 0) {
            await this.finalizeFile(uriStr, true);
        }
        else {
            this.codeLensProvider.refresh();
            this.refreshVisibleEditorDecorations(uriStr, activeDiff.changes);
            this.focusNextHunk(uriStr, index);
        }
    }
    /**
     * Rejects a specific hunk inside a file.
     * @public
     * @param {(undefined|string|!tsickle_vscode_1.Uri)=} targetUri
     * @param {(undefined|number)=} index
     * @return {!Promise<void>}
     */
    async rejectHunk(targetUri, index) {
        if (targetUri == null || index == null) {
            return;
        }
        /** @type {string} */
        const uriStr = typeof targetUri === 'string' ? targetUri : (/** @type {!tsickle_vscode_1.Uri} */ (targetUri)).toString();
        /** @type {(undefined|!ActiveDiff)} */
        const activeDiff = this.activeDiffs.get(uriStr);
        if (!activeDiff) {
            console.warn(`[Antigravity] rejectHunk failed: no active diff found for uriStr: ${uriStr}`);
            return;
        }
        /** @type {!tsickle_inline_diff_change_range_7.InlineDiffChangeRange} */
        const rangeToResolve = activeDiff.changes.ranges[index];
        if (!rangeToResolve) {
            console.warn(`[Antigravity] rejectHunk failed: no range found at index: ${index}`);
            return;
        }
        /** @type {!Array<string>} */
        const insertions = rangeToResolve.modifiedText
            ? rangeToResolve.modifiedText.split('\n')
            : [];
        /** @type {!Array<string>} */
        const deletions = rangeToResolve.originalText
            ? rangeToResolve.originalText.split('\n')
            : [];
        /** @type {string} */
        const hunkHash = (0, hunk_storage_1.computeHunkHash)(insertions, deletions);
        this.onDidResolveHunkEmitter.fire({
            uri: activeDiff.uri,
            hunkIndex: index,
            accept: false,
            hunkHash,
        });
        /** @type {!Array<!tsickle_inline_diff_change_range_7.InlineDiffChangeRange>} */
        const remainingRanges = activeDiff.changes.ranges.filter((/**
         * @param {!tsickle_inline_diff_change_range_7.InlineDiffChangeRange} _
         * @param {number} i
         * @return {boolean}
         */
        (_, i) => i !== index));
        /** @type {!tsickle_vscode_1.TextDocument} */
        const document = await vscode.workspace.openTextDocument(activeDiff.uri);
        if (rangeToResolve.additionRange) {
            /** @type {!tsickle_vscode_1.Range} */
            const rangeToDelete = new vscode.Range(rangeToResolve.additionRange.start, document.lineAt(rangeToResolve.additionRange.end.line).rangeIncludingLineBreak.end);
            /** @type {!tsickle_vscode_1.WorkspaceEdit} */
            const edit = new vscode.WorkspaceEdit();
            edit.delete(activeDiff.uri, rangeToDelete);
            this.isResolvingHunk = true;
            await vscode.workspace.applyEdit(edit);
            this.isResolvingHunk = false;
            /** @type {!tsickle_vscode_1.TextDocumentContentChangeEvent} */
            const changeEvent = {
                range: rangeToDelete,
                text: '',
                rangeLength: document.offsetAt(rangeToDelete.end) -
                    document.offsetAt(rangeToDelete.start),
                rangeOffset: document.offsetAt(rangeToDelete.start),
            };
            activeDiff.changes.ranges = (0, inline_diff_range_tracker_1.recalculateInlineDiffRanges)(remainingRanges, [
                changeEvent,
            ]);
        }
        else {
            activeDiff.changes.ranges = remainingRanges;
        }
        activeDiff.combinedText = document.getText();
        if (document.isDirty) {
            await document.save();
        }
        if (activeDiff.changes.ranges.length === 0) {
            await this.finalizeFile(uriStr, false);
        }
        else {
            this.codeLensProvider.refresh();
            this.refreshVisibleEditorDecorations(uriStr, activeDiff.changes);
            this.focusNextHunk(uriStr, index);
        }
    }
    /**
     * Scrolls the editor to reveal and select the next remaining hunk after a hunk resolution.
     * @private
     * @param {string} uriStr
     * @param {number} resolvedIndex
     * @return {void}
     */
    focusNextHunk(uriStr, resolvedIndex) {
        /** @type {(undefined|!ActiveDiff)} */
        const activeDiff = this.activeDiffs.get(uriStr);
        if (!activeDiff || activeDiff.changes.ranges.length === 0) {
            return;
        }
        /** @type {string} */
        const targetUri = activeDiff.uri.toString();
        /** @type {(undefined|!tsickle_vscode_1.TextEditor)} */
        const editor = (0, utils_1.findEditorForUri)(targetUri);
        if (!editor)
            return;
        // Target the same index (which now points to the next hunk) or clamp to the last remaining hunk.
        /** @type {number} */
        const nextIndex = Math.min(resolvedIndex, activeDiff.changes.ranges.length - 1);
        /** @type {!tsickle_inline_diff_change_range_7.InlineDiffChangeRange} */
        const nextHunk = activeDiff.changes.ranges[nextIndex];
        if (!nextHunk)
            return;
        /** @type {(undefined|!tsickle_vscode_1.Range)} */
        const targetRange = nextHunk.additionRange ?? nextHunk.deletionRange;
        if (targetRange) {
            editor.revealRange(targetRange, vscode.TextEditorRevealType.InCenter);
            editor.selection = new vscode.Selection(targetRange.start, targetRange.start);
        }
    }
    /**
     * Accepts all pending changes in a file.
     * @public
     * @param {(undefined|string|!tsickle_vscode_1.Uri)=} uri
     * @return {!Promise<void>}
     */
    async acceptAll(uri) {
        /** @type {(undefined|string|!tsickle_vscode_1.Uri)} */
        const targetUri = uri ?? vscode.window.activeTextEditor?.document.uri;
        if (!targetUri) {
            return;
        }
        /** @type {string} */
        const uriStr = typeof targetUri === 'string' ? targetUri : (/** @type {!tsickle_vscode_1.Uri} */ (targetUri)).toString();
        /** @type {(undefined|!ActiveDiff)} */
        const activeDiff = this.activeDiffs.get(uriStr);
        if (!activeDiff) {
            console.warn(`[Antigravity] acceptAll failed: no active diff found for uriStr: ${uriStr}`);
            return;
        }
        /** @type {!tsickle_vscode_1.TextDocument} */
        const document = await vscode.workspace.openTextDocument(activeDiff.uri);
        await this.applyContentReplacement(document, activeDiff.modifiedText);
        await this.finalizeFile(uriStr, true);
    }
    /**
     * Rejects all pending changes in a file.
     * @public
     * @param {(undefined|string|!tsickle_vscode_1.Uri)=} uri
     * @return {!Promise<void>}
     */
    async rejectAll(uri) {
        /** @type {(undefined|string|!tsickle_vscode_1.Uri)} */
        const targetUri = uri ?? vscode.window.activeTextEditor?.document.uri;
        if (!targetUri) {
            return;
        }
        /** @type {string} */
        const uriStr = typeof targetUri === 'string' ? targetUri : (/** @type {!tsickle_vscode_1.Uri} */ (targetUri)).toString();
        /** @type {(undefined|!ActiveDiff)} */
        const activeDiff = this.activeDiffs.get(uriStr);
        if (!activeDiff) {
            console.warn(`[Antigravity] rejectAll failed: no active diff found for uriStr: ${uriStr}`);
            return;
        }
        /** @type {!tsickle_vscode_1.TextDocument} */
        const document = await vscode.workspace.openTextDocument(activeDiff.uri);
        await this.applyContentReplacement(document, activeDiff.originalText);
        await this.finalizeFile(uriStr, false);
    }
    /**
     * Reverts all registered diff files to their original state and disposes resource hooks.
     * @public
     * @return {!Promise<void>}
     */
    async cleanUpAll() {
        for (const activeDiff of this.activeDiffs.values()) {
            try {
                /** @type {!tsickle_vscode_1.TextDocument} */
                const document = await vscode.workspace.openTextDocument(activeDiff.uri);
                await this.revertDocument(document, activeDiff.originalText);
            }
            catch (e) {
                console.error('[Antigravity] Revert failed on cleanup for:', activeDiff.uri.toString(), e);
            }
        }
        this.activeDiffs.clear();
        this.onDidChangeActiveDiffsEmitter.fire();
    }
    /**
     * @public
     * @return {void}
     */
    dispose() {
        this.cleanUpAll()
            .then((/**
         * @return {void}
         */
        () => {
            this.disposables.forEach((/**
             * @param {!tsickle_vscode_1.Disposable} d
             * @return {void}
             */
            (d) => {
                d.dispose();
            }));
        }))
            .catch((/**
         * @param {?} e
         * @return {void}
         */
        (e) => {
            console.error('[Antigravity] Error during dispose cleanup:', e);
        }));
    }
    // ---------------------------------------------------------------------------
    // Private Helpers
    // ---------------------------------------------------------------------------
    /**
     * @private
     * @param {!tsickle_vscode_1.TextEditor} editor
     * @param {!ActiveDiff} activeDiff
     * @return {!Promise<void>}
     */
    async showDiffInEditor(editor, activeDiff) {
        this.applyDecorations(editor, activeDiff.changes);
    }
    /**
     * @private
     * @param {!tsickle_vscode_1.TextDocument} document
     * @param {string} text
     * @return {!Promise<void>}
     */
    async applyContentReplacement(document, text) {
        /** @type {!tsickle_vscode_1.WorkspaceEdit} */
        const edit = new vscode.WorkspaceEdit();
        /** @type {!tsickle_vscode_1.Range} */
        const fullRange = new vscode.Range(new vscode.Position(0, 0), document.lineAt(document.lineCount - 1).range.end);
        edit.replace(document.uri, fullRange, text);
        this.isResolvingHunk = true;
        await vscode.workspace.applyEdit(edit);
        this.isResolvingHunk = false;
    }
    /**
     * @private
     * @param {!tsickle_vscode_1.TextEditor} editor
     * @param {!tsickle_inline_diff_changes_4.InlineDiffChanges} changes
     * @return {void}
     */
    applyDecorations(editor, changes) {
        /** @type {!Array<!tsickle_vscode_1.Range>} */
        const additionRanges = changes.ranges
            .map((/**
         * @param {!tsickle_inline_diff_change_range_7.InlineDiffChangeRange} r
         * @return {(undefined|!tsickle_vscode_1.Range)}
         */
        (r) => r.additionRange))
            .filter((/**
         * @param {(undefined|!tsickle_vscode_1.Range)} r
         * @return {boolean}
         */
        (r) => !!r));
        /** @type {!Array<!tsickle_vscode_1.Range>} */
        const deletionRanges = changes.ranges
            .map((/**
         * @param {!tsickle_inline_diff_change_range_7.InlineDiffChangeRange} r
         * @return {(undefined|!tsickle_vscode_1.Range)}
         */
        (r) => r.deletionRange))
            .filter((/**
         * @param {(undefined|!tsickle_vscode_1.Range)} r
         * @return {boolean}
         */
        (r) => !!r));
        editor.setDecorations(this.styles.add.base, additionRanges);
        editor.setDecorations(this.styles.delete.base, deletionRanges);
        this.applyBorderDecorations(editor, additionRanges, 'add');
        this.applyBorderDecorations(editor, deletionRanges, 'delete');
    }
    /**
     * @private
     * @param {!tsickle_vscode_1.TextEditor} editor
     * @param {!Array<!tsickle_vscode_1.Range>} ranges
     * @param {string} type
     * @return {void}
     */
    applyBorderDecorations(editor, ranges, type) {
        /** @type {!Array<!tsickle_vscode_1.Range>} */
        const singleLine = [];
        /** @type {!Array<!tsickle_vscode_1.Range>} */
        const top = [];
        /** @type {!Array<!tsickle_vscode_1.Range>} */
        const mid = [];
        /** @type {!Array<!tsickle_vscode_1.Range>} */
        const bottom = [];
        /** @type {number} */
        const lineCount = editor.document.lineCount;
        for (const range of ranges) {
            if (range.start.line < 0 ||
                range.start.line >= lineCount ||
                range.end.line < 0 ||
                range.end.line >= lineCount) {
                continue;
            }
            if (range.isSingleLine) {
                singleLine.push(range);
            }
            else {
                top.push(editor.document.lineAt(range.start.line).range);
                if (range.end.line > range.start.line + 1) {
                    /** @type {number} */
                    const midStartLine = range.start.line + 1;
                    /** @type {number} */
                    const midEndLine = range.end.line - 1;
                    mid.push(new vscode.Range(new vscode.Position(midStartLine, 0), editor.document.lineAt(midEndLine).range.end));
                }
                bottom.push(editor.document.lineAt(range.end.line).range);
            }
        }
        /** @type {!DiffStyleGroup} */
        const typeStyles = type === 'add' ? this.styles.add : this.styles.delete;
        editor.setDecorations(typeStyles.single, singleLine);
        editor.setDecorations(typeStyles.top, top);
        editor.setDecorations(typeStyles.mid, mid);
        editor.setDecorations(typeStyles.bottom, bottom);
    }
    /**
     * @private
     * @param {!tsickle_vscode_1.TextEditor} editor
     * @return {void}
     */
    clearDecorations(editor) {
        for (const group of [this.styles.add, this.styles.delete]) {
            for (const style of Object.values(group)) {
                editor.setDecorations(style, []);
            }
        }
    }
    /**
     * @private
     * @param {!tsickle_vscode_1.TextDocumentChangeEvent} event
     * @return {void}
     */
    handleDocumentEdit(event) {
        if (this.isResolvingHunk)
            return;
        /** @type {string} */
        const key = event.document.uri.toString();
        /** @type {(undefined|!ActiveDiff)} */
        const activeDiff = this.activeDiffs.get(key);
        if (!activeDiff || !activeDiff.hasBeenShown)
            return;
        activeDiff.changes.ranges = (0, inline_diff_range_tracker_1.recalculateInlineDiffRanges)(activeDiff.changes.ranges, event.contentChanges);
        activeDiff.combinedText = event.document.getText();
        this.refreshVisibleEditorDecorations(key, activeDiff.changes);
        this.codeLensProvider.refresh();
    }
    /**
     * @private
     * @param {!tsickle_vscode_1.TextEditor} editor
     * @return {!Promise<void>}
     */
    async handleActiveEditorChange(editor) {
        /** @type {string} */
        const key = editor.document.uri.toString();
        /** @type {(undefined|!ActiveDiff)} */
        const activeDiff = this.activeDiffs.get(key);
        if (activeDiff) {
            await this.showDiffInEditor(editor, activeDiff);
            await vscode.commands.executeCommand('setContext', 'antigravity.hasActiveDiff', true);
        }
        else {
            this.clearDecorations(editor);
            await vscode.commands.executeCommand('setContext', 'antigravity.hasActiveDiff', false);
        }
    }
    /**
     * @private
     * @param {!tsickle_vscode_1.TextDocument} document
     * @return {!Promise<void>}
     */
    async handleDocumentClose(document) {
        /** @type {string} */
        const key = document.uri.toString();
        /** @type {(undefined|!ActiveDiff)} */
        const activeDiff = this.activeDiffs.get(key);
        if (!activeDiff)
            return;
        await this.rejectRemaining(key);
    }
    /**
     * @private
     * @param {string} uriStr
     * @return {!Promise<void>}
     */
    async rejectRemaining(uriStr) {
        /** @type {(undefined|!ActiveDiff)} */
        const activeDiff = this.activeDiffs.get(uriStr);
        if (!activeDiff)
            return;
        /** @type {!tsickle_vscode_1.TextDocument} */
        const document = await vscode.workspace.openTextDocument(activeDiff.uri);
        /** @type {!tsickle_vscode_1.WorkspaceEdit} */
        const edit = new vscode.WorkspaceEdit();
        // Revert unresolved changes by deleting addition ranges
        for (const range of activeDiff.changes.ranges) {
            if (range.additionRange) {
                /** @type {!tsickle_vscode_1.Range} */
                const rangeToDelete = new vscode.Range(range.additionRange.start, document.lineAt(range.additionRange.end.line).rangeIncludingLineBreak.end);
                edit.delete(activeDiff.uri, rangeToDelete);
            }
        }
        this.isResolvingHunk = true;
        await vscode.workspace.applyEdit(edit);
        this.isResolvingHunk = false;
        if (document.isDirty) {
            await document.save();
        }
        await this.finalizeFile(uriStr, false);
    }
    /**
     * @private
     * @param {!tsickle_vscode_1.TextDocument} document
     * @param {string} originalText
     * @return {!Promise<void>}
     */
    async revertDocument(document, originalText) {
        await this.applyContentReplacement(document, originalText);
        if (document.isDirty) {
            await document.save();
        }
    }
    /**
     * @private
     * @param {string} uriStr
     * @param {boolean} accepted
     * @return {!Promise<void>}
     */
    async finalizeFile(uriStr, accepted) {
        /** @type {(undefined|!ActiveDiff)} */
        const activeDiff = this.activeDiffs.get(uriStr);
        if (!activeDiff)
            return;
        /** @type {!tsickle_vscode_1.TextDocument} */
        const document = await vscode.workspace.openTextDocument(activeDiff.uri);
        if (document.isDirty) {
            await document.save();
        }
        this.activeDiffs.delete(uriStr);
        this.onDidChangeActiveDiffsEmitter.fire();
        this.codeLensProvider.refresh();
        await vscode.commands.executeCommand('setContext', 'antigravity.hasActiveDiff', false);
        for (const editor of vscode.window.visibleTextEditors) {
            if (editor.document.uri.toString() === uriStr) {
                this.clearDecorations(editor);
            }
        }
        this.onDidFinalizeFileEmitter.fire({
            uri: activeDiff.uri,
            accepted,
            modifiedText: activeDiff.modifiedText,
        });
    }
    /**
     * @private
     * @param {string} uriStr
     * @param {!tsickle_inline_diff_changes_4.InlineDiffChanges} changes
     * @return {void}
     */
    refreshVisibleEditorDecorations(uriStr, changes) {
        for (const editor of vscode.window.visibleTextEditors) {
            if (editor.document.uri.toString() === uriStr) {
                this.applyDecorations(editor, changes);
            }
        }
    }
    /**
     * @private
     * @return {void}
     */
    refreshAllVisibleDecorations() {
        for (const editor of vscode.window.visibleTextEditors) {
            /** @type {string} */
            const key = editor.document.uri.toString();
            /** @type {(undefined|!ActiveDiff)} */
            const activeDiff = this.activeDiffs.get(key);
            if (activeDiff) {
                this.applyDecorations(editor, activeDiff.changes);
            }
            else {
                this.clearDecorations(editor);
            }
        }
    }
}
exports.InlineDiffManager = InlineDiffManager;
/* istanbul ignore if */
if (false) {
    /**
     * @const {!Map<string, !ActiveDiff>}
     * @private
     */
    InlineDiffManager.prototype.activeDiffs;
    /**
     * @const {!Array<!tsickle_vscode_1.Disposable>}
     * @private
     */
    InlineDiffManager.prototype.disposables;
    /**
     * @const {!InlineDiffCodeLensProvider}
     * @private
     */
    InlineDiffManager.prototype.codeLensProvider;
    /**
     * @type {boolean}
     * @private
     */
    InlineDiffManager.prototype.isResolvingHunk;
    /**
     * @const {!tsickle_vscode_1.EventEmitter<{uri: !tsickle_vscode_1.Uri, accepted: boolean, modifiedText: string}>}
     * @private
     */
    InlineDiffManager.prototype.onDidFinalizeFileEmitter;
    /**
     * @const {!tsickle_vscode_1.Event<{uri: !tsickle_vscode_1.Uri, accepted: boolean, modifiedText: string}>}
     * @public
     */
    InlineDiffManager.prototype.onDidFinalizeFile;
    /**
     * @const {!tsickle_vscode_1.EventEmitter<{uri: !tsickle_vscode_1.Uri, hunkIndex: number, accept: boolean, hunkHash: string}>}
     * @private
     */
    InlineDiffManager.prototype.onDidResolveHunkEmitter;
    /**
     * @const {!tsickle_vscode_1.Event<{uri: !tsickle_vscode_1.Uri, hunkIndex: number, accept: boolean, hunkHash: string}>}
     * @public
     */
    InlineDiffManager.prototype.onDidResolveHunk;
    /**
     * @const {!tsickle_vscode_1.EventEmitter<void>}
     * @private
     */
    InlineDiffManager.prototype.onDidChangeActiveDiffsEmitter;
    /**
     * @const {!tsickle_vscode_1.Event<void>}
     * @public
     */
    InlineDiffManager.prototype.onDidChangeActiveDiffs;
    /**
     * @const {!DiffStyles}
     * @private
     */
    InlineDiffManager.prototype.styles;
}
/**
 * TextDocumentContentProvider providing original document content from register Diff states.
 * @implements {tsickle_vscode_1.TextDocumentContentProvider}
 */
class OriginalDocumentProvider {
    /**
     * @public
     * @param {!InlineDiffManager} manager
     */
    constructor(manager) {
        this.manager = manager;
    }
    /**
     * @public
     * @param {!tsickle_vscode_1.Uri} uri
     * @return {string}
     */
    provideTextDocumentContent(uri) {
        /** @type {string} */
        const cleanPath = decodeURIComponent(uri.path).replace(/^\//, '');
        /** @type {(undefined|!ActiveDiff)} */
        const activeDiff = this.manager.getActiveDiff(cleanPath);
        return activeDiff ? activeDiff.originalText : '';
    }
}
/* istanbul ignore if */
if (false) {
    /**
     * @const {!InlineDiffManager}
     * @private
     */
    OriginalDocumentProvider.prototype.manager;
}
/**
 * CodeLensProvider generating Accept/Reject buttons above active hunks.
 * @implements {tsickle_vscode_1.CodeLensProvider<!tsickle_vscode_1.CodeLens>}
 */
class InlineDiffCodeLensProvider {
    /**
     * @public
     * @param {!InlineDiffManager} manager
     */
    constructor(manager) {
        this.manager = manager;
        this.changeEmitter = new vscode.EventEmitter();
        this.onDidChangeCodeLenses = this.changeEmitter.event;
    }
    /**
     * @public
     * @param {!tsickle_vscode_1.TextDocument} document
     * @param {!tsickle_vscode_1.CancellationToken} token
     * @return {!Array<!tsickle_vscode_1.CodeLens>}
     */
    provideCodeLenses(document, token) {
        /** @type {(undefined|!ActiveDiff)} */
        const activeDiff = this.manager.getActiveDiff(document.uri.toString());
        if (!activeDiff ||
            !activeDiff.changes.exists() ||
            token.isCancellationRequested) {
            return [];
        }
        /** @type {!Array<!tsickle_vscode_1.CodeLens>} */
        const codeLenses = [];
        for (const [index__tsickle_destructured_1, range__tsickle_destructured_2] of activeDiff.changes.ranges.entries()) {
            const index = /** @type {number} */ (index__tsickle_destructured_1);
            const range = /** @type {!tsickle_inline_diff_change_range_7.InlineDiffChangeRange} */ (range__tsickle_destructured_2);
            /** @type {!tsickle_vscode_1.Position} */
            const position = new vscode.Position(range.start, 0);
            /** @type {!tsickle_vscode_1.Range} */
            const codeLensRange = new vscode.Range(position, position);
            codeLenses.push(new vscode.CodeLens(codeLensRange, {
                title: '$(check) Accept',
                tooltip: 'Accept this suggestion block',
                command: 'antigravity.inlineDiff.accept',
                arguments: [document.uri.toString(), index],
            }), new vscode.CodeLens(codeLensRange, {
                title: '$(chrome-close) Reject',
                tooltip: 'Reject this suggestion block',
                command: 'antigravity.inlineDiff.reject',
                arguments: [document.uri.toString(), index],
            }));
        }
        return codeLenses;
    }
    /**
     * @public
     * @return {void}
     */
    refresh() {
        this.changeEmitter.fire();
    }
}
/* istanbul ignore if */
if (false) {
    /**
     * @const {!tsickle_vscode_1.EventEmitter<void>}
     * @private
     */
    InlineDiffCodeLensProvider.prototype.changeEmitter;
    /**
     * @const {!tsickle_vscode_1.Event<void>}
     * @public
     */
    InlineDiffCodeLensProvider.prototype.onDidChangeCodeLenses;
    /**
     * @const {!InlineDiffManager}
     * @private
     */
    InlineDiffCodeLensProvider.prototype.manager;
}
